//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UWPHook.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangeLanguage {
            get {
                return ((bool)(this["ChangeLanguage"]));
            }
            set {
                this["ChangeLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TargetLanguage {
            get {
                return ((string)(this["TargetLanguage"]));
            }
            set {
                this["TargetLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Seconds {
            get {
                return ((int)(this["Seconds"]));
            }
            set {
                this["Seconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StreamMode {
            get {
                return ((bool)(this["StreamMode"]));
            }
            set {
                this["StreamMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamGridDbApiKey {
            get {
                return ((string)(this["SteamGridDbApiKey"]));
            }
            set {
                this["SteamGridDbApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedSteamGridDB_Style {
            get {
                return ((int)(this["SelectedSteamGridDB_Style"]));
            }
            set {
                this["SelectedSteamGridDB_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedSteamGridDB_Type {
            get {
                return ((int)(this["SelectedSteamGridDB_Type"]));
            }
            set {
                this["SelectedSteamGridDB_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedSteamGridDB_nfsw {
            get {
                return ((int)(this["SelectedSteamGridDB_nfsw"]));
            }
            set {
                this["SelectedSteamGridDB_nfsw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedSteamGridDB_Humor {
            get {
                return ((int)(this["SelectedSteamGridDB_Humor"]));
            }
            set {
                this["SelectedSteamGridDB_Humor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OfferedSteamGridDB {
            get {
                return ((bool)(this["OfferedSteamGridDB"]));
            }
            set {
                this["OfferedSteamGridDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("READY TO PLAY,XBOX")]
        public string Tags {
            get {
                return ((string)(this["Tags"]));
            }
            set {
                this["Tags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>any</string>
  <string>alternate</string>
  <string>blurred</string>
  <string>white_logo</string>
  <string>material</string>
  <string>no_logo </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SteamGridDB_Style {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SteamGridDB_Style"]));
            }
            set {
                this["SteamGridDB_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>any</string>\r\n  <string>static</string>\r\n  <string>animated</string>\r\n</Ar" +
            "rayOfString>")]
        public global::System.Collections.Specialized.StringCollection SteamGridDB_Type {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SteamGridDB_Type"]));
            }
            set {
                this["SteamGridDB_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>false</string>\r\n  <string>any</string>\r\n  <string>true</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection SteamGridDB_nfsw {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SteamGridDB_nfsw"]));
            }
            set {
                this["SteamGridDB_nfsw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>false</string>\r\n  <string>any</string>\r\n  <string>true</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection SteamGridDB_Humor {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SteamGridDB_Humor"]));
            }
            set {
                this["SteamGridDB_Humor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>ERROR</string>\r\n  <string>DEBUG</string>\r\n  <string>TRACE</string>\r\n</Arra" +
            "yOfString>")]
        public global::System.Collections.Specialized.StringCollection LogLevel {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LogLevel"]));
            }
            set {
                this["LogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedLogLevel {
            get {
                return ((int)(this["SelectedLogLevel"]));
            }
            set {
                this["SelectedLogLevel"] = value;
            }
        }
    }
}
